{
 "title": "ICMP Ping Status of WMS Servers",
 "description": "在同一看板下展示TCP,ICMP,HTTPS的状态监控，优化各图表展示效果，支持多服务同时展示。",
 "tags": [
  "StarsL.cn",
  "Prometheus",
  "blackbox_exporter"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "blackbox",
    "query": "label_values(probe_success,exporter)"
   },
   {
    "name": "job",
    "query": "label_values(up{exporter=~\"$blackbox\"},job)"
   },
   {
    "name": "env",
    "label": "env",
    "query": "label_values(up{job=~'$job'},env)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(up{job=~'$job',env=~'$env'},service)"
   },
   {
    "name": "gametype",
    "label": "gametype",
    "query": "label_values(up{job=~'$job',env=~'$env',service=~'$service'},gametype)"
   },
   {
    "name": "targets",
    "label": "targets",
    "query": "label_values(up{job=~'$job',env=~'$env',service=~'$service',gametype=~'$gametype'},instance)"
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Ping Latency for $targets",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=~'$job',instance=~'$targets'}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Ping Stats Details",
   "type": "table",
   "gridPos": { "h": 19, "w": 14, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$targets\"} - 0"
    }
   ]
  },
  {
   "title": "Ping Stats Overall (0=Offline, 1=Online)",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " count_values('value',probe_success{job=~'$job'})",
     "legendFormat": "{{ value }}"
    }
   ]
  }
 ]
}