{
 "title": "Infiniband",
 "description": "Use Prometheus to collect the stats on a entire Infiniband fabric from a single management node.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "MLX5 Firmware Version",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (instance, hca_type,firmware_version) (node_infiniband_info{device=\"mlx5_0\"})"
    },
    {}
   ]
  },
  { "title": "Informative", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "RX (Bytes/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(node_infiniband_port_data_received_bytes_total[5m]))",
     "legendFormat": "Received {{instance}}"
    }
   ]
  },
  {
   "title": "TX (Bytes/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(topk(10,rate(node_infiniband_port_data_transmitted_bytes_total[5m])))",
     "legendFormat": "Transmitted {{instance}}"
    }
   ]
  },
  {
   "title": "Data Transmit Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(node_infiniband_port_data_transmitted_bytes_total[2m])*8) != 0",
     "legendFormat": "Transmit {{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "Data Receive Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(node_infiniband_port_data_received_bytes_total[2m])*8) != 0",
     "legendFormat": "Receive {{instance}}-{{device}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Errors (should be empty)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(node_infiniband_port_constraint_errors_received_total[2m])) != 0",
     "legendFormat": "packets discarded"
    },
    {
     "expr": "topk(10,rate(node_infiniband_port_constraint_errors_transmitted_total[2m])) != 0",
     "legendFormat": "packets not transmitted"
    },
    {
     "expr": "topk(10,rate(node_infiniband_port_errors_received_total[2m])) != 0",
     "legendFormat": "packets received containing error"
    }
   ]
  },
  {
   "title": "Transmit Waits (should be empty)",
   "type": "graph",
   "description": "Number of ticks during which the port had data to transmit but no data was sent during the entire tick",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(node_infiniband_port_transmit_wait_total[2m])) != 0",
     "legendFormat": "transmit waits"
    }
   ]
  },
  {
   "title": "Transmit Discarded (should be empty)",
   "type": "graph",
   "description": "Number of outbound packets discarded by the port because the port is down or congested",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(node_infiniband_port_discards_transmitted_total[2m])) != 0",
     "legendFormat": "transmit discards"
    }
   ]
  },
  {
   "title": "Links Down (should be empty)",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "node_infiniband_link_downed_total != 0",
     "legendFormat": "link_downed_total-{{instance}}-{{device}}"
    }
   ]
  }
 ]
}