{
 "title": "WMS SSI GSP1 GC dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "cleanupService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last GC Duration - cleanupService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"cleanupService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - cleanupService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"cleanupService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - cleanupService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"cleanupService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "pickToLightService_5_2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Last GC Duration - pickToLightService_5_2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_5_2\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - pickToLightService_5_2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_5_2\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - pickToLightService_5_2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_5_2\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "reorganisationService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Last GC Duration - reorganisationService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"reorganisationService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - reorganisationService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"reorganisationService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - reorganisationService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"reorganisationService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "antMainServ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Last GC Duration - antMainServ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"antMainServ\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - antMainServ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"antMainServ\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - antMainServ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"antMainServ\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "recvSorterMFSService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Last GC Duration - recvSorterMFSService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"recvSorterMFSService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - recvSorterMFSService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"recvSorterMFSService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - recvSorterMFSService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"recvSorterMFSService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "commonMFSAdapterService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Last GC Duration - commonMFSAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"commonMFSAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - commonMFSAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"commonMFSAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - commonMFSAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"commonMFSAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "pickToLightService_3_1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Last GC Duration - pickToLightService_3_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_3_1\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - pickToLightService_3_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_3_1\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - pickToLightService_3_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_3_1\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "dataWarehouseUserPerformanceService",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 }
  },
  {
   "title": "Last GC Duration - dataWarehouseUserPerformanceService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"dataWarehouseUserPerformanceService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - dataWarehouseUserPerformanceService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"dataWarehouseUserPerformanceService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - dataWarehouseUserPerformanceService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"dataWarehouseUserPerformanceService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostInterfaceOutgoingService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Last GC Duration - hostInterfaceOutgoingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"hostInterfaceOutgoingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostInterfaceOutgoingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"hostInterfaceOutgoingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostInterfaceOutgoingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 73 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"hostInterfaceOutgoingService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "loggingService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Last GC Duration - loggingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"loggingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - loggingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"loggingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - loggingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 82 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"loggingService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "cmcPackingMachineService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Last GC Duration - cmcPackingMachineService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"cmcPackingMachineService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - cmcPackingMachineService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"cmcPackingMachineService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - cmcPackingMachineService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 91 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"cmcPackingMachineService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "messagingService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Last GC Duration - messagingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"messagingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - messagingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"messagingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - messagingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 100 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"messagingService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "consolidationService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Last GC Duration - consolidationService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"consolidationService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - consolidationService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"consolidationService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - consolidationService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 109 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"consolidationService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "reservationService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Last GC Duration - reservationService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"reservationService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - reservationService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"reservationService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - reservationService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 118 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"reservationService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "receivingService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "Last GC Duration - receivingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"receivingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - receivingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"receivingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - receivingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 127 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"receivingService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "pickToLightService_1_2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 } },
  {
   "title": "Last GC Duration - pickToLightService_1_2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_1_2\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - pickToLightService_1_2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_1_2\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - pickToLightService_1_2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 136 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_1_2\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "pickToLightService_6_1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 } },
  {
   "title": "Last GC Duration - pickToLightService_6_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_6_1\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - pickToLightService_6_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_6_1\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - pickToLightService_6_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 145 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_6_1\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "recvSorterMFSAdapterService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 } },
  {
   "title": "Last GC Duration - recvSorterMFSAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 154 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"recvSorterMFSAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - recvSorterMFSAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 154 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"recvSorterMFSAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - recvSorterMFSAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 154 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"recvSorterMFSAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "pickToLightService_5_1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 162 } },
  {
   "title": "Last GC Duration - pickToLightService_5_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 163 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_5_1\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - pickToLightService_5_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 163 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_5_1\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - pickToLightService_5_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 163 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_5_1\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "shippingSorterHostDBAdapterService",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 171 }
  },
  {
   "title": "Last GC Duration - shippingSorterHostDBAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 172 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"shippingSorterHostDBAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - shippingSorterHostDBAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 172 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"shippingSorterHostDBAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - shippingSorterHostDBAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 172 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"shippingSorterHostDBAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "dataWarehouseTuTrackerService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 180 } },
  {
   "title": "Last GC Duration - dataWarehouseTuTrackerService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"dataWarehouseTuTrackerService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - dataWarehouseTuTrackerService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"dataWarehouseTuTrackerService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - dataWarehouseTuTrackerService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 181 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"dataWarehouseTuTrackerService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "pickToLightService_2_2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 189 } },
  {
   "title": "Last GC Duration - pickToLightService_2_2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 190 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_2_2\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - pickToLightService_2_2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 190 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_2_2\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - pickToLightService_2_2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 190 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_2_2\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "scsSocAdapterService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 198 } },
  {
   "title": "Last GC Duration - scsSocAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 199 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"scsSocAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - scsSocAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 199 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"scsSocAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - scsSocAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 199 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"scsSocAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "dataWarehouseService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 207 } },
  {
   "title": "Last GC Duration - dataWarehouseService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 208 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"dataWarehouseService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - dataWarehouseService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 208 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"dataWarehouseService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - dataWarehouseService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 208 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"dataWarehouseService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "birtPDFPrinting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 216 } },
  {
   "title": "Last GC Duration - birtPDFPrinting",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 217 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"birtPDFPrinting\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - birtPDFPrinting",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 217 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"birtPDFPrinting\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - birtPDFPrinting",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 217 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"birtPDFPrinting\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "slPickToLightService_1_1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 225 } },
  {
   "title": "Last GC Duration - slPickToLightService_1_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 226 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"slPickToLightService_1_1\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - slPickToLightService_1_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 226 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"slPickToLightService_1_1\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - slPickToLightService_1_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 226 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"slPickToLightService_1_1\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "singleLineService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 234 } },
  {
   "title": "Last GC Duration - singleLineService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 235 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"singleLineService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - singleLineService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 235 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"singleLineService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - singleLineService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 235 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"singleLineService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "dataWarehouseMessagingService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 243 } },
  {
   "title": "Last GC Duration - dataWarehouseMessagingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 244 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"dataWarehouseMessagingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - dataWarehouseMessagingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 244 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"dataWarehouseMessagingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - dataWarehouseMessagingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 244 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"dataWarehouseMessagingService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostInterfaceModelService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 252 } },
  {
   "title": "Last GC Duration - hostInterfaceModelService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 253 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"hostInterfaceModelService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostInterfaceModelService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 253 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"hostInterfaceModelService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostInterfaceModelService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 253 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"hostInterfaceModelService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "monitoringService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 261 } },
  {
   "title": "Last GC Duration - monitoringService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 262 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"monitoringService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - monitoringService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 262 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"monitoringService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - monitoringService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 262 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"monitoringService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "pickToLightService_3_2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 270 } },
  {
   "title": "Last GC Duration - pickToLightService_3_2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 271 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_3_2\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - pickToLightService_3_2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 271 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_3_2\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - pickToLightService_3_2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 271 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_3_2\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "commonWMSAdapterService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 279 } },
  {
   "title": "Last GC Duration - commonWMSAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 280 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"commonWMSAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - commonWMSAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 280 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"commonWMSAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - commonWMSAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 280 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"commonWMSAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "stocktakingService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 288 } },
  {
   "title": "Last GC Duration - stocktakingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 289 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"stocktakingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - stocktakingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 289 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"stocktakingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - stocktakingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 289 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"stocktakingService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "pickToLightService_4_2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 297 } },
  {
   "title": "Last GC Duration - pickToLightService_4_2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 298 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_4_2\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - pickToLightService_4_2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 298 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_4_2\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - pickToLightService_4_2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 298 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_4_2\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "binSocAdapterService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 306 } },
  {
   "title": "Last GC Duration - binSocAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 307 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"binSocAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - binSocAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 307 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"binSocAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - binSocAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 307 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"binSocAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "recvSorterWMSAdapterService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 315 } },
  {
   "title": "Last GC Duration - recvSorterWMSAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 316 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"recvSorterWMSAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - recvSorterWMSAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 316 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"recvSorterWMSAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - recvSorterWMSAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 316 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"recvSorterWMSAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "pickToLightService_6_2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 324 } },
  {
   "title": "Last GC Duration - pickToLightService_6_2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 325 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_6_2\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - pickToLightService_6_2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 325 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_6_2\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - pickToLightService_6_2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 325 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_6_2\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "pickToLightService_1_1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 333 } },
  {
   "title": "Last GC Duration - pickToLightService_1_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 334 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_1_1\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - pickToLightService_1_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 334 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_1_1\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - pickToLightService_1_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 334 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_1_1\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "recvSorterSOCAdapterService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 342 } },
  {
   "title": "Last GC Duration - recvSorterSOCAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 343 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"recvSorterSOCAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - recvSorterSOCAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 343 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"recvSorterSOCAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - recvSorterSOCAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 343 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"recvSorterSOCAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "pickToLightService_2_1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 351 } },
  {
   "title": "Last GC Duration - pickToLightService_2_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 352 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_2_1\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - pickToLightService_2_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 352 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_2_1\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - pickToLightService_2_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 352 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_2_1\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "scsMFSService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 360 } },
  {
   "title": "Last GC Duration - scsMFSService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 361 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"scsMFSService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - scsMFSService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 361 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"scsMFSService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - scsMFSService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 361 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"scsMFSService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "mqAdapterService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 369 } },
  {
   "title": "Last GC Duration - mqAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 370 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"mqAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mqAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 370 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"mqAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mqAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 370 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"mqAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "schedulerService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 378 } },
  {
   "title": "Last GC Duration - schedulerService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 379 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"schedulerService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - schedulerService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 379 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"schedulerService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - schedulerService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 379 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"schedulerService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "pickToLightService_4_1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 387 } },
  {
   "title": "Last GC Duration - pickToLightService_4_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 388 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_4_1\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - pickToLightService_4_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 388 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_4_1\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - pickToLightService_4_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 388 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"pickToLightService_4_1\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "binMFSService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 396 } },
  {
   "title": "Last GC Duration - binMFSService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 397 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"binMFSService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - binMFSService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 397 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"binMFSService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - binMFSService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 397 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"binMFSService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "demandService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 405 } },
  {
   "title": "Last GC Duration - demandService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 406 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"demandService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - demandService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 406 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"demandService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - demandService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 406 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"demandService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "replenishmentService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 414 } },
  {
   "title": "Last GC Duration - replenishmentService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 415 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"replenishmentService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - replenishmentService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 415 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"replenishmentService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - replenishmentService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 415 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"replenishmentService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostInterfaceIncomingService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 423 } },
  {
   "title": "Last GC Duration - hostInterfaceIncomingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 424 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"hostInterfaceIncomingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostInterfaceIncomingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 424 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"hostInterfaceIncomingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostInterfaceIncomingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 424 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"hostInterfaceIncomingService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "materialImageService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 432 } },
  {
   "title": "Last GC Duration - materialImageService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 433 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"materialImageService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - materialImageService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 433 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"materialImageService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - materialImageService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 433 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"materialImageService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "movementOrderService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 441 } },
  {
   "title": "Last GC Duration - movementOrderService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 442 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"movementOrderService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - movementOrderService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 442 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"movementOrderService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - movementOrderService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 442 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"movementOrderService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "orderPrioritizationService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 450 } },
  {
   "title": "Last GC Duration - orderPrioritizationService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 451 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"orderPrioritizationService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - orderPrioritizationService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 451 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"orderPrioritizationService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - orderPrioritizationService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 451 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"orderPrioritizationService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "scanDataService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 459 } },
  {
   "title": "Last GC Duration - scanDataService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 460 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"scanDataService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - scanDataService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 460 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"scanDataService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - scanDataService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 460 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"scanDataService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "shipTrailerService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 468 } },
  {
   "title": "Last GC Duration - shipTrailerService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 469 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"shipTrailerService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - shipTrailerService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 469 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"shipTrailerService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - shipTrailerService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 469 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"shipTrailerService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "userPerformanceService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 477 } },
  {
   "title": "Last GC Duration - userPerformanceService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 478 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"userPerformanceService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - userPerformanceService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 478 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"userPerformanceService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - userPerformanceService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 478 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"userPerformanceService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "printingService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 486 } },
  {
   "title": "Last GC Duration - printingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 487 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"printingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - printingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 487 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"printingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - printingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 487 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"printingService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "dialogService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 495 } },
  {
   "title": "Last GC Duration - dialogService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 496 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"dialogService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - dialogService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 496 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"dialogService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - dialogService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 496 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7031\", job=\"telegraf\", oop=\"dialogService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  }
 ]
}