{
 "title": "WMS SSI IND1 GC dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "mfsAdapterBinConveyor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last GC Duration - mfsAdapterBinConveyor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsAdapterBinConveyor\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsAdapterBinConveyor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsAdapterBinConveyor\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsAdapterBinConveyor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsAdapterBinConveyor\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "antMainServ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Last GC Duration - antMainServ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"antMainServ\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - antMainServ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"antMainServ\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - antMainServ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"antMainServ\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "webDialogPickModuleService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Last GC Duration - webDialogPickModuleService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"webDialogPickModuleService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - webDialogPickModuleService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"webDialogPickModuleService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - webDialogPickModuleService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"webDialogPickModuleService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "wmsAdapterPickingSorter21", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Last GC Duration - wmsAdapterPickingSorter21",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"wmsAdapterPickingSorter21\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - wmsAdapterPickingSorter21",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"wmsAdapterPickingSorter21\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - wmsAdapterPickingSorter21",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"wmsAdapterPickingSorter21\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "shippingTrailerService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Last GC Duration - shippingTrailerService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"shippingTrailerService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - shippingTrailerService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"shippingTrailerService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - shippingTrailerService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"shippingTrailerService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "customerOrderService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Last GC Duration - customerOrderService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"customerOrderService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - customerOrderService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"customerOrderService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - customerOrderService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"customerOrderService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "mfsPickingSorter21", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Last GC Duration - mfsPickingSorter21",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsPickingSorter21\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsPickingSorter21",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsPickingSorter21\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsPickingSorter21",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsPickingSorter21\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostUDCService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Last GC Duration - hostUDCService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostUDCService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostUDCService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostUDCService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostUDCService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostUDCService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "statisticsService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Last GC Duration - statisticsService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"statisticsService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - statisticsService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"statisticsService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - statisticsService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 73 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"statisticsService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "mfsBinConveyor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Last GC Duration - mfsBinConveyor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsBinConveyor\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsBinConveyor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsBinConveyor\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsBinConveyor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 82 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsBinConveyor\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostYMS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Last GC Duration - hostYMS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostYMS\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostYMS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostYMS\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostYMS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 91 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostYMS\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "datawarehouseService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Last GC Duration - datawarehouseService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"datawarehouseService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - datawarehouseService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"datawarehouseService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - datawarehouseService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 100 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"datawarehouseService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "messaging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Last GC Duration - messaging",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"messaging\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - messaging",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"messaging\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - messaging",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 109 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"messaging\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "mfsAdapterIntelligratedReceivingSorterService",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 }
  },
  {
   "title": "Last GC Duration - mfsAdapterIntelligratedReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsAdapterIntelligratedReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsAdapterIntelligratedReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsAdapterIntelligratedReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsAdapterIntelligratedReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 118 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsAdapterIntelligratedReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostSiras", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "Last GC Duration - hostSiras",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostSiras\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostSiras",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostSiras\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostSiras",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 127 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostSiras\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "mfsPickingSorter22", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 } },
  {
   "title": "Last GC Duration - mfsPickingSorter22",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsPickingSorter22\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsPickingSorter22",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsPickingSorter22\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsPickingSorter22",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 136 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsPickingSorter22\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostCubiScan", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 } },
  {
   "title": "Last GC Duration - hostCubiScan",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostCubiScan\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostCubiScan",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostCubiScan\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostCubiScan",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 145 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostCubiScan\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostWmsAdapter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 } },
  {
   "title": "Last GC Duration - hostWmsAdapter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 154 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostWmsAdapter\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostWmsAdapter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 154 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostWmsAdapter\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostWmsAdapter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 154 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostWmsAdapter\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "dialogService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 162 } },
  {
   "title": "Last GC Duration - dialogService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 163 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"dialogService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - dialogService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 163 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"dialogService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - dialogService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 163 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"dialogService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "houseKeepingService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 171 } },
  {
   "title": "Last GC Duration - houseKeepingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 172 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"houseKeepingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - houseKeepingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 172 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"houseKeepingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - houseKeepingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 172 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"houseKeepingService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "wmsAdapterBinConveyor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 180 } },
  {
   "title": "Last GC Duration - wmsAdapterBinConveyor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"wmsAdapterBinConveyor\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - wmsAdapterBinConveyor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"wmsAdapterBinConveyor\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - wmsAdapterBinConveyor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 181 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"wmsAdapterBinConveyor\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "packOrderReleaseService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 189 } },
  {
   "title": "Last GC Duration - packOrderReleaseService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 190 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"packOrderReleaseService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - packOrderReleaseService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 190 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"packOrderReleaseService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - packOrderReleaseService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 190 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"packOrderReleaseService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "wmsAdapterPickingSorter22", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 198 } },
  {
   "title": "Last GC Duration - wmsAdapterPickingSorter22",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 199 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"wmsAdapterPickingSorter22\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - wmsAdapterPickingSorter22",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 199 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"wmsAdapterPickingSorter22\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - wmsAdapterPickingSorter22",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 199 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"wmsAdapterPickingSorter22\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "socAdapterIntelligratedReceivingSorterService",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 207 }
  },
  {
   "title": "Last GC Duration - socAdapterIntelligratedReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 208 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"socAdapterIntelligratedReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - socAdapterIntelligratedReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 208 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"socAdapterIntelligratedReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - socAdapterIntelligratedReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 208 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"socAdapterIntelligratedReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostScheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 216 } },
  {
   "title": "Last GC Duration - hostScheduler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 217 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostScheduler\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostScheduler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 217 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostScheduler\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostScheduler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 217 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostScheduler\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "mfsIntelligratedReceivingSorterService",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 225 }
  },
  {
   "title": "Last GC Duration - mfsIntelligratedReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 226 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsIntelligratedReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsIntelligratedReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 226 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsIntelligratedReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsIntelligratedReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 226 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsIntelligratedReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "socAdapterPickingSorter22", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 234 } },
  {
   "title": "Last GC Duration - socAdapterPickingSorter22",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 235 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"socAdapterPickingSorter22\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - socAdapterPickingSorter22",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 235 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"socAdapterPickingSorter22\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - socAdapterPickingSorter22",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 235 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"socAdapterPickingSorter22\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "datawarehouseMessaging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 243 } },
  {
   "title": "Last GC Duration - datawarehouseMessaging",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 244 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"datawarehouseMessaging\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - datawarehouseMessaging",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 244 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"datawarehouseMessaging\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - datawarehouseMessaging",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 244 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"datawarehouseMessaging\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostGeC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 252 } },
  {
   "title": "Last GC Duration - hostGeC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 253 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostGeC\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostGeC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 253 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostGeC\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostGeC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 253 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostGeC\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "demandService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 261 } },
  {
   "title": "Last GC Duration - demandService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 262 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"demandService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - demandService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 262 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"demandService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - demandService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 262 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"demandService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "webReportingService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 270 } },
  {
   "title": "Last GC Duration - webReportingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 271 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"webReportingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - webReportingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 271 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"webReportingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - webReportingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 271 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"webReportingService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "socAdapterPickingSorter21", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 279 } },
  {
   "title": "Last GC Duration - socAdapterPickingSorter21",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 280 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"socAdapterPickingSorter21\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - socAdapterPickingSorter21",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 280 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"socAdapterPickingSorter21\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - socAdapterPickingSorter21",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 280 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"socAdapterPickingSorter21\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "mfsShippingSorter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 288 } },
  {
   "title": "Last GC Duration - mfsShippingSorter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 289 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsShippingSorter\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsShippingSorter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 289 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsShippingSorter\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsShippingSorter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 289 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsShippingSorter\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostHazmat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 297 } },
  {
   "title": "Last GC Duration - hostHazmat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 298 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostHazmat\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostHazmat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 298 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostHazmat\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostHazmat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 298 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostHazmat\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "webDialogPutwallService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 306 } },
  {
   "title": "Last GC Duration - webDialogPutwallService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 307 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"webDialogPutwallService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - webDialogPutwallService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 307 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"webDialogPutwallService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - webDialogPutwallService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 307 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"webDialogPutwallService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "mfsAdapterShippingSorter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 315 } },
  {
   "title": "Last GC Duration - mfsAdapterShippingSorter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 316 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsAdapterShippingSorter\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsAdapterShippingSorter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 316 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsAdapterShippingSorter\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsAdapterShippingSorter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 316 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsAdapterShippingSorter\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "webDesktopServiceDeveloper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 324 } },
  {
   "title": "Last GC Duration - webDesktopServiceDeveloper",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 325 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"webDesktopServiceDeveloper\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - webDesktopServiceDeveloper",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 325 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"webDesktopServiceDeveloper\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - webDesktopServiceDeveloper",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 325 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"webDesktopServiceDeveloper\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostHost", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 333 } },
  {
   "title": "Last GC Duration - hostHost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 334 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostHost\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostHost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 334 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostHost\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostHost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 334 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostHost\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "socAdapterShippingSorter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 342 } },
  {
   "title": "Last GC Duration - socAdapterShippingSorter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 343 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"socAdapterShippingSorter\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - socAdapterShippingSorter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 343 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"socAdapterShippingSorter\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - socAdapterShippingSorter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 343 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"socAdapterShippingSorter\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "mfsAdapterPickingSorter22", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 351 } },
  {
   "title": "Last GC Duration - mfsAdapterPickingSorter22",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 352 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsAdapterPickingSorter22\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsAdapterPickingSorter22",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 352 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsAdapterPickingSorter22\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsAdapterPickingSorter22",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 352 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsAdapterPickingSorter22\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "lmsService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 360 } },
  {
   "title": "Last GC Duration - lmsService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 361 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"lmsService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - lmsService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 361 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"lmsService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - lmsService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 361 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"lmsService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostScanData", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 369 } },
  {
   "title": "Last GC Duration - hostScanData",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 370 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostScanData\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostScanData",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 370 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostScanData\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostScanData",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 370 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"hostScanData\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "mfsStatisticsDwhService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 378 } },
  {
   "title": "Last GC Duration - mfsStatisticsDwhService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 379 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsStatisticsDwhService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsStatisticsDwhService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 379 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsStatisticsDwhService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsStatisticsDwhService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 379 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsStatisticsDwhService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "printing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 387 } },
  {
   "title": "Last GC Duration - printing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 388 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"printing\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - printing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 388 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"printing\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - printing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 388 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"printing\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "socAdapterBinConveyor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 396 } },
  {
   "title": "Last GC Duration - socAdapterBinConveyor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 397 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"socAdapterBinConveyor\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - socAdapterBinConveyor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 397 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"socAdapterBinConveyor\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - socAdapterBinConveyor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 397 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"socAdapterBinConveyor\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "mfsAdapterPickingSorter21", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 405 } },
  {
   "title": "Last GC Duration - mfsAdapterPickingSorter21",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 406 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsAdapterPickingSorter21\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsAdapterPickingSorter21",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 406 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsAdapterPickingSorter21\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsAdapterPickingSorter21",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 406 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"mfsAdapterPickingSorter21\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 414 } },
  {
   "title": "Last GC Duration - scheduler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 415 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"scheduler\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - scheduler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 415 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"scheduler\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - scheduler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 415 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"scheduler\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "webDialogService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 423 } },
  {
   "title": "Last GC Duration - webDialogService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 424 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"webDialogService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - webDialogService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 424 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"webDialogService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - webDialogService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 424 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"webDialogService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "socAdapterPackageMachine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 432 } },
  {
   "title": "Last GC Duration - socAdapterPackageMachine",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 433 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"socAdapterPackageMachine\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - socAdapterPackageMachine",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 433 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"socAdapterPackageMachine\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - socAdapterPackageMachine",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 433 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"socAdapterPackageMachine\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "wmsAdapterIntelligratedReceivingSorterService",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 441 }
  },
  {
   "title": "Last GC Duration - wmsAdapterIntelligratedReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 442 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"wmsAdapterIntelligratedReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - wmsAdapterIntelligratedReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 442 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"wmsAdapterIntelligratedReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - wmsAdapterIntelligratedReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 442 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"wmsAdapterIntelligratedReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "webDesktopService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 450 } },
  {
   "title": "Last GC Duration - webDesktopService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 451 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"webDesktopService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - webDesktopService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 451 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"webDesktopService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - webDesktopService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 451 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"webDesktopService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "cleanup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 459 } },
  {
   "title": "Last GC Duration - cleanup",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 460 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"cleanup\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - cleanup",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 460 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"cleanup\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - cleanup",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 460 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"cleanup\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "wmsAdapterShippingSorter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 468 } },
  {
   "title": "Last GC Duration - wmsAdapterShippingSorter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 469 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"wmsAdapterShippingSorter\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - wmsAdapterShippingSorter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 469 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"wmsAdapterShippingSorter\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - wmsAdapterShippingSorter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 469 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:6280\", job=\"telegraf\", oop=\"wmsAdapterShippingSorter\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  }
 ]
}