{
 "title": "WMS SSI MCO1 GC dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "webReportingService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last GC Duration - webReportingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"webReportingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - webReportingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"webReportingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - webReportingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"webReportingService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "socAdapterReceivingSorterService",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Last GC Duration - socAdapterReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"socAdapterReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - socAdapterReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"socAdapterReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - socAdapterReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"socAdapterReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "dialogService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Last GC Duration - dialogService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"dialogService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - dialogService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"dialogService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - dialogService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"dialogService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "mfsAdapterBinConveyorService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Last GC Duration - mfsAdapterBinConveyorService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsAdapterBinConveyorService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsAdapterBinConveyorService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsAdapterBinConveyorService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsAdapterBinConveyorService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsAdapterBinConveyorService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "antMainServ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Last GC Duration - antMainServ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"antMainServ\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - antMainServ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"antMainServ\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - antMainServ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"antMainServ\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "messagingService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Last GC Duration - messagingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"messagingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - messagingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"messagingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - messagingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"messagingService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "mfsBinConveyorService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Last GC Duration - mfsBinConveyorService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsBinConveyorService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsBinConveyorService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsBinConveyorService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsBinConveyorService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsBinConveyorService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "lmsService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Last GC Duration - lmsService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"lmsService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - lmsService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"lmsService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - lmsService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"lmsService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostHostService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Last GC Duration - hostHostService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostHostService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostHostService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostHostService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostHostService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 73 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostHostService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostHazmatService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Last GC Duration - hostHazmatService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostHazmatService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostHazmatService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostHazmatService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostHazmatService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 82 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostHazmatService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostCubiScanService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Last GC Duration - hostCubiScanService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostCubiScanService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostCubiScanService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostCubiScanService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostCubiScanService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 91 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostCubiScanService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "dataWarehouseService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Last GC Duration - dataWarehouseService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"dataWarehouseService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - dataWarehouseService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"dataWarehouseService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - dataWarehouseService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 100 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"dataWarehouseService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "socAdapterShippingSorterService",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 }
  },
  {
   "title": "Last GC Duration - socAdapterShippingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"socAdapterShippingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - socAdapterShippingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"socAdapterShippingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - socAdapterShippingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 109 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"socAdapterShippingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "packOrderReleaseService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Last GC Duration - packOrderReleaseService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"packOrderReleaseService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - packOrderReleaseService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"packOrderReleaseService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - packOrderReleaseService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 118 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"packOrderReleaseService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "mfsAdapterPickingSorter22Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 }
  },
  {
   "title": "Last GC Duration - mfsAdapterPickingSorter22Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsAdapterPickingSorter22Service\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsAdapterPickingSorter22Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsAdapterPickingSorter22Service\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsAdapterPickingSorter22Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 127 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsAdapterPickingSorter22Service\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostUDCService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 } },
  {
   "title": "Last GC Duration - hostUDCService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostUDCService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostUDCService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostUDCService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostUDCService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 136 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostUDCService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "wmsAdapterReceivingSorterService",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 }
  },
  {
   "title": "Last GC Duration - wmsAdapterReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"wmsAdapterReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - wmsAdapterReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"wmsAdapterReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - wmsAdapterReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 145 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"wmsAdapterReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "socAdapterPickingSorter21Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 }
  },
  {
   "title": "Last GC Duration - socAdapterPickingSorter21Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 154 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"socAdapterPickingSorter21Service\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - socAdapterPickingSorter21Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 154 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"socAdapterPickingSorter21Service\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - socAdapterPickingSorter21Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 154 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"socAdapterPickingSorter21Service\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "mfsAdapterPickingSorter21Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 162 }
  },
  {
   "title": "Last GC Duration - mfsAdapterPickingSorter21Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 163 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsAdapterPickingSorter21Service\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsAdapterPickingSorter21Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 163 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsAdapterPickingSorter21Service\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsAdapterPickingSorter21Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 163 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsAdapterPickingSorter21Service\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostGeCService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 171 } },
  {
   "title": "Last GC Duration - hostGeCService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 172 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostGeCService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostGeCService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 172 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostGeCService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostGeCService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 172 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostGeCService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "printingService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 180 } },
  {
   "title": "Last GC Duration - printingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"printingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - printingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"printingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - printingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 181 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"printingService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "wmsAdapterBinConveyorService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 189 } },
  {
   "title": "Last GC Duration - wmsAdapterBinConveyorService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 190 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"wmsAdapterBinConveyorService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - wmsAdapterBinConveyorService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 190 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"wmsAdapterBinConveyorService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - wmsAdapterBinConveyorService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 190 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"wmsAdapterBinConveyorService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostWTMSService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 198 } },
  {
   "title": "Last GC Duration - hostWTMSService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 199 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostWTMSService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostWTMSService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 199 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostWTMSService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostWTMSService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 199 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostWTMSService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "houseKeepingService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 207 } },
  {
   "title": "Last GC Duration - houseKeepingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 208 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"houseKeepingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - houseKeepingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 208 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"houseKeepingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - houseKeepingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 208 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"houseKeepingService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "mfsAdapterReceivingSorterService",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 216 }
  },
  {
   "title": "Last GC Duration - mfsAdapterReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 217 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsAdapterReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsAdapterReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 217 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsAdapterReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsAdapterReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 217 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsAdapterReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "mfsStatisticsDwhService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 225 } },
  {
   "title": "Last GC Duration - mfsStatisticsDwhService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 226 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsStatisticsDwhService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsStatisticsDwhService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 226 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsStatisticsDwhService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsStatisticsDwhService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 226 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsStatisticsDwhService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "socAdapterPickingSorter22Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 234 }
  },
  {
   "title": "Last GC Duration - socAdapterPickingSorter22Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 235 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"socAdapterPickingSorter22Service\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - socAdapterPickingSorter22Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 235 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"socAdapterPickingSorter22Service\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - socAdapterPickingSorter22Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 235 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"socAdapterPickingSorter22Service\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostWmsAdapterService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 243 } },
  {
   "title": "Last GC Duration - hostWmsAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 244 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostWmsAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostWmsAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 244 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostWmsAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostWmsAdapterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 244 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostWmsAdapterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "webDialogService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 252 } },
  {
   "title": "Last GC Duration - webDialogService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 253 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"webDialogService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - webDialogService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 253 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"webDialogService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - webDialogService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 253 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"webDialogService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostSchedulerService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 261 } },
  {
   "title": "Last GC Duration - hostSchedulerService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 262 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostSchedulerService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostSchedulerService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 262 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostSchedulerService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostSchedulerService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 262 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostSchedulerService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostYMSService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 270 } },
  {
   "title": "Last GC Duration - hostYMSService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 271 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostYMSService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostYMSService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 271 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostYMSService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostYMSService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 271 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostYMSService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "mfsReceivingSorterService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 279 } },
  {
   "title": "Last GC Duration - mfsReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 280 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 280 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsReceivingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 280 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsReceivingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "socAdapterBinConveyorService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 288 } },
  {
   "title": "Last GC Duration - socAdapterBinConveyorService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 289 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"socAdapterBinConveyorService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - socAdapterBinConveyorService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 289 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"socAdapterBinConveyorService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - socAdapterBinConveyorService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 289 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"socAdapterBinConveyorService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "wmsAdapterShippingSorterService",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 297 }
  },
  {
   "title": "Last GC Duration - wmsAdapterShippingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 298 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"wmsAdapterShippingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - wmsAdapterShippingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 298 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"wmsAdapterShippingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - wmsAdapterShippingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 298 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"wmsAdapterShippingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "mfsPickingSorter22Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 306 } },
  {
   "title": "Last GC Duration - mfsPickingSorter22Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 307 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsPickingSorter22Service\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsPickingSorter22Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 307 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsPickingSorter22Service\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsPickingSorter22Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 307 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsPickingSorter22Service\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "mfsAdapterShippingSorterService",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 315 }
  },
  {
   "title": "Last GC Duration - mfsAdapterShippingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 316 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsAdapterShippingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsAdapterShippingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 316 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsAdapterShippingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsAdapterShippingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 316 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsAdapterShippingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostScanDataService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 324 } },
  {
   "title": "Last GC Duration - hostScanDataService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 325 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostScanDataService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostScanDataService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 325 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostScanDataService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostScanDataService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 325 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostScanDataService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "demandService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 333 } },
  {
   "title": "Last GC Duration - demandService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 334 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"demandService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - demandService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 334 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"demandService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - demandService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 334 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"demandService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "cleanupService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 342 } },
  {
   "title": "Last GC Duration - cleanupService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 343 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"cleanupService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - cleanupService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 343 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"cleanupService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - cleanupService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 343 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"cleanupService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "mfsPickingSorter21Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 351 } },
  {
   "title": "Last GC Duration - mfsPickingSorter21Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 352 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsPickingSorter21Service\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsPickingSorter21Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 352 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsPickingSorter21Service\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsPickingSorter21Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 352 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsPickingSorter21Service\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "hostSIRASService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 360 } },
  {
   "title": "Last GC Duration - hostSIRASService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 361 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostSIRASService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - hostSIRASService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 361 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostSIRASService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - hostSIRASService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 361 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"hostSIRASService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "wmsAdapterPickingSorter21Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 369 }
  },
  {
   "title": "Last GC Duration - wmsAdapterPickingSorter21Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 370 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"wmsAdapterPickingSorter21Service\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - wmsAdapterPickingSorter21Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 370 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"wmsAdapterPickingSorter21Service\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - wmsAdapterPickingSorter21Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 370 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"wmsAdapterPickingSorter21Service\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "shippingTrailerService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 378 } },
  {
   "title": "Last GC Duration - shippingTrailerService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 379 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"shippingTrailerService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - shippingTrailerService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 379 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"shippingTrailerService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - shippingTrailerService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 379 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"shippingTrailerService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "mfsShippingSorterService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 387 } },
  {
   "title": "Last GC Duration - mfsShippingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 388 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsShippingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsShippingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 388 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsShippingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsShippingSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 388 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsShippingSorterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "customerOrderService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 396 } },
  {
   "title": "Last GC Duration - customerOrderService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 397 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"customerOrderService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - customerOrderService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 397 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"customerOrderService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - customerOrderService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 397 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"customerOrderService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "wmsAdapterPickingSorter22Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 405 }
  },
  {
   "title": "Last GC Duration - wmsAdapterPickingSorter22Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 406 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"wmsAdapterPickingSorter22Service\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - wmsAdapterPickingSorter22Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 406 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"wmsAdapterPickingSorter22Service\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - wmsAdapterPickingSorter22Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 406 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"wmsAdapterPickingSorter22Service\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "schedulerService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 414 } },
  {
   "title": "Last GC Duration - schedulerService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 415 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"schedulerService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - schedulerService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 415 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"schedulerService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - schedulerService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 415 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"schedulerService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "datawarehouseMessagingService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 423 } },
  {
   "title": "Last GC Duration - datawarehouseMessagingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 424 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"datawarehouseMessagingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - datawarehouseMessagingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 424 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"datawarehouseMessagingService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - datawarehouseMessagingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 424 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"datawarehouseMessagingService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "mfsPouchSorterService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 432 } },
  {
   "title": "Last GC Duration - mfsPouchSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 433 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsPouchSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsPouchSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 433 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsPouchSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsPouchSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 433 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsPouchSorterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "mfsAdapterPouchSorterService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 441 } },
  {
   "title": "Last GC Duration - mfsAdapterPouchSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 442 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsAdapterPouchSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - mfsAdapterPouchSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 442 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsAdapterPouchSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - mfsAdapterPouchSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 442 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"mfsAdapterPouchSorterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "webDesktopService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 450 } },
  {
   "title": "Last GC Duration - webDesktopService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 451 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"webDesktopService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - webDesktopService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 451 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"webDesktopService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - webDesktopService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 451 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"webDesktopService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "webDialogPickModuleService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 459 } },
  {
   "title": "Last GC Duration - webDialogPickModuleService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 460 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"webDialogPickModuleService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - webDialogPickModuleService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 460 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"webDialogPickModuleService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - webDialogPickModuleService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 460 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"webDialogPickModuleService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "webWorkerPouchSorterService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 468 } },
  {
   "title": "Last GC Duration - webWorkerPouchSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 469 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"webWorkerPouchSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - webWorkerPouchSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 469 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"webWorkerPouchSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - webWorkerPouchSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 469 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"webWorkerPouchSorterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "cmcPackingMachineService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 477 } },
  {
   "title": "Last GC Duration - cmcPackingMachineService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 478 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"cmcPackingMachineService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - cmcPackingMachineService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 478 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"cmcPackingMachineService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - cmcPackingMachineService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 478 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"cmcPackingMachineService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "wmsAdapterPouchSorterService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 486 } },
  {
   "title": "Last GC Duration - wmsAdapterPouchSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 487 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"wmsAdapterPouchSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - wmsAdapterPouchSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 487 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"wmsAdapterPouchSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - wmsAdapterPouchSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 487 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"wmsAdapterPouchSorterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "socAdapterPouchSorterService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 495 } },
  {
   "title": "Last GC Duration - socAdapterPouchSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 496 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"socAdapterPouchSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - socAdapterPouchSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 496 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"socAdapterPouchSorterService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - socAdapterPouchSorterService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 496 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"socAdapterPouchSorterService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "webDialogPutwallService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 504 } },
  {
   "title": "Last GC Duration - webDialogPutwallService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 505 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"webDialogPutwallService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - webDialogPutwallService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 505 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"webDialogPutwallService\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - webDialogPutwallService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 505 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"webDialogPutwallService\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "webDesktopServiceDeveloper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 513 } },
  {
   "title": "Last GC Duration - webDesktopServiceDeveloper",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 514 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_duration {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"webDesktopServiceDeveloper\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Duration"
    }
   ]
  },
  {
   "title": "Last GC Thread Count - webDesktopServiceDeveloper",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 514 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wms_gc_markandsweep_LastGcInfo_GcThreadCount {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"webDesktopServiceDeveloper\", oot=\"custpromise\"}",
     "legendFormat": "Last GC Thread Count"
    }
   ]
  },
  {
   "title": "CPU Usage - webDesktopServiceDeveloper",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 514 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wms_cpu_usage_ProcessCpuLoad {host=\"mon.wms.walmart.com\",instance=\"10.46.39.75:7853\", job=\"telegraf\", oop=\"webDesktopServiceDeveloper\", oot=\"custpromise\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  }
 ]
}